import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "../components/Navbar";
import Image from "next/image";
import { BsInstagram, BsFacebook, BsLinkedin } from "react-icons/bs";

export default function Home() {
  const Router = useRouter();

  function toContactMe() {
    Router.push({
      pathname: "/contact",
    });
  }

  return (
    <div>
      <Head>
        <title>Andrian Junior | Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src="/../public/assets/me2.png"
        alt="/"
        width="500"
        height="500"
        className="float-right mr-16 py-10"
      ></Image>
      <br></br>
      <div className="mt-20 px-64">
        <div className="w-full h-24 py-10  text-5xl font-serif text-[#F3EFE0] border-blue-500">
          Hi There,
        </div>
        <div className="w-full h-16 text-2xl py-3 font-serif text-[#F3EFE0] border-blue-500 animate-pulse">
          I'm Andrian Junior , Full Stack Developer
        </div>
        <div className="w-full text-[#F3EFE0] font-serif">
          A college student who passionate in Software Engineering, Backend and
          Frontend Development.
        </div>
        <div className="w-full h-20 py-5">
          <button
            type="button"
            className=" h-13 w-15 p-2 bg-[#F49D1A] rounded-xl"
            onClick={() => toContactMe()}
          >
            <div className="text-[#282A3A] font-serif"> Contact Me </div>
          </button>
        </div>
        <br></br>
        <div className="grid grid-flow-col auto-cols-max gap-4">
          <div className="text-[#F3EFE0] w-10 h-10">
            <button
              type="button"
              onClick={() =>
                window.open("https://www.instagram.com/andriann08/")
              }
            >
              <BsInstagram size="medium"></BsInstagram>
            </button>
          </div>
          <div className="text-[#F3EFE0] w-10 h-10">
            <button
              type="button"
              onClick={() =>
                window.open("https://www.facebook.com/junior.andrian/")
              }
            >
              <BsFacebook size="medium"></BsFacebook>
            </button>
          </div>
          <div className="text-[#F3EFE0] w-10 h-10">
            <button
              type="button"
              onClick={() =>
                window.open("https://www.linkedin.com/in/andrian-karloys/")
              }
            >
              <BsLinkedin size="medium"></BsLinkedin>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
